export default {
  chapter: 3,
  title: '小李在箱根',
  lesson: [
    {
      no: 9,
      topic: '四川料理は辛いです',
      basic: [],
      utilization: [],
      grammar: [],
      word: [
        { kana: 'りょうり', mana: '料理', type: '名', cn: '菜肴，饭菜' },
        { kana: 'しせんりょうり', mana: '四川料理', type: '名', cn: '四川菜' },
        { kana: 'スープ', mana: '', type: '名', cn: '汤' },
        { kana: 'ペキンダック', mana: '北京ダック', type: '名', cn: '北京烤鸭' },
        { kana: 'たべもの', mana: '食べ物', type: '名', cn: '食物，食品' },
        { kana: 'すきやき', mana: 'すき焼き', type: '名', cn: '日式牛肉火锅' },
        { kana: 'おんせん', mana: '温泉', type: '名', cn: '温泉' },
        { kana: 'おゆ', mana: 'お湯', type: '名', cn: '热水，开水' },
        { kana: 'みず', mana: '水', type: '名', cn: '水，凉水' },
        { kana: 'ゆかた', mana: '浴衣', type: '名', cn: '浴衣，夏季和服' },
        { kana: 'ながめ', mana: '眺め', type: '名', cn: '景色，风景' },
        { kana: 'くすり', mana: '薬', type: '名', cn: '药' },
        { kana: 'てんき', mana: '天気', type: '名', cn: '天气' },
        { kana: 'うみ', mana: '海', type: '名', cn: '大海' },
        { kana: 'やま', mana: '山', type: '名', cn: '山' },
        { kana: 'かみ', mana: '紙', type: '名', cn: '纸' },
        { kana: 'ニュース', mana: '', type: '名', cn: '新闻' },
        { kana: 'じょせい', mana: '女性', type: '名', cn: '女性' },
        { kana: 'おきゃくさま', mana: 'お客様', type: '名', cn: '来宾' },
        { kana: 'グラス', mana: '', type: '名', cn: '玻璃杯' },
        { kana: 'かぶき', mana: '歌舞伎', type: '名', cn: '歌舞伎' },
        { kana: 'きもち', mana: '気持ち', type: '名', cn: '心情' },
        { kana: 'たくさん', mana: '', type: '名', cn: '很多' },
        { kana: 'からい', mana: '辛い', type: '形1', cn: '辣' },
        { kana: 'あまい', mana: '甘い', type: '形1', cn: '甜' },
        { kana: 'しおからい', mana: '塩辛い', type: '形1', cn: '咸' },
        { kana: 'しょっぱい', mana: '', type: '形1', cn: '咸' },
        { kana: 'すっぱい', mana: '酸っぱい', type: '形1', cn: '酸' },
        { kana: 'にがい', mana: '苦い', type: '形1', cn: '苦' },
        { kana: 'おいしい', mana: '', type: '形1', cn: '好吃，可口' },
        { kana: 'まずい', mana: '', type: '形1', cn: '不好吃，难吃' },
        { kana: 'あつい', mana: '熱い', type: '形1', cn: '热，烫' },
        { kana: 'つめたい', mana: '冷たい', type: '形1', cn: '凉' },
        { kana: 'たのしい', mana: '楽しい', type: '形1', cn: '愉快，快乐' },
        { kana: 'おもしろい', mana: '', type: '形1', cn: '有趣，有意思' },
        { kana: 'つまらない', mana: '', type: '形1', cn: '无聊' },
        { kana: 'ひろい', mana: '広い', type: '形1', cn: '广阔，宽敞' },
        { kana: 'せまい', mana: '狭い', type: '形1', cn: '狭窄' },
        { kana: 'おおきい', mana: '大きい', type: '形1', cn: '大' },
        { kana: 'ちいさい', mana: '小さい', type: '形1', cn: '小' },
        { kana: 'いそがしい', mana: '忙しい', type: '形1', cn: '忙，忙碌' },
        { kana: 'いい', mana: '', type: '形1', cn: '好' },
        { kana: 'わるい', mana: '悪い', type: '形1', cn: '不好，坏' },
        { kana: 'すばらしい', mana: '', type: '形1', cn: '极好，绝佳' },
        { kana: 'とおい', mana: '遠い', type: '形1', cn: '远' },
        { kana: 'ちかい', mana: '近い', type: '形1', cn: '近' },
        { kana: 'たかい', mana: '高い', type: '形1', cn: '高，贵' },
        { kana: 'ひくい', mana: '低い', type: '形1', cn: '低' },
        { kana: 'やすい', mana: '安い', type: '形1', cn: '便宜' },
        { kana: 'さむい', mana: '寒い', type: '形1', cn: '寒冷' },
        { kana: 'あつい', mana: '暑い', type: '形1', cn: '（天气）热' },
        { kana: 'あおい', mana: '青い', type: '形1', cn: '蓝色的' },
        { kana: 'しろい', mana: '白い', type: '形1', cn: '白色的' },
        { kana: 'あたらしい', mana: '新しい', type: '形1', cn: '新' },
        { kana: 'ふるい', mana: '古い', type: '形1', cn: '旧' },
        { kana: 'むずかしい', mana: '難しい', type: '形1', cn: '难' },
        { kana: 'やさしい', mana: '易しい', type: '形1', cn: '容易' },
        { kana: 'おおい', mana: '多い', type: '形1', cn: '多' },
        { kana: 'すくない', mana: '少ない', type: '形1', cn: '少' },
        { kana: 'かわいい', mana: '', type: '形1', cn: '可爱' },
        { kana: 'ほんとうに', mana: '本当に', type: '副', cn: '真的，实在是' },
        { kana: 'あまり', mana: '', type: '副', cn: '不（太）～，不很～' },
        { kana: 'とても', mana: '', type: '副', cn: '很，非常' },
        { kana: 'たいへん', mana: '', type: '副', cn: '很，非常' },
        { kana: 'すこし', mana: '少し', type: '副', cn: '一点儿' },
        { kana: 'ちょっと', mana: '', type: '副', cn: '一点儿' },
        { kana: 'ぜんぜん', mana: '全然', type: '副', cn: '根本（不），全然（不）' },
        { kana: 'ちょうど', mana: '', type: '副', cn: '正好，恰好' },
        { kana: 'あら', mana: '', type: '叹', cn: '哎呀，咦' },
        { kana: 'あれ', mana: '', type: '叹', cn: '哎呀，咦' },
        { kana: 'ああ', mana: '', type: '叹', cn: '啊' },
        { kana: 'てんあんもん', mana: '天安門', type: '专', cn: '天安门' },
        { kana: 'ばんりのちょうじょう', mana: '万里の長城', type: '专', cn: '万里长城' }
      ],
      phrase: [
        { kana: 'きもちがいい', mana: '気持ちがいい', cn: '感觉舒服，心情愉快' },
        { kana: '〜用', mana: '', cn: '' }
      ]
    },
    {
      no: 10,
      topic: '京都の紅葉は有名です',
      basic: [],
      utilization: [],
      grammar: [],
      word: [
        { kana: 'もみじ', mana: '紅葉', type: '名', cn: '红叶' },
        { kana: 'こきょう', mana: '故郷', type: '名', cn: '故乡' },
        { kana: 'とおり', mana: '通り', type: '名', cn: '大街' },
        { kana: 'まち', mana: '町', type: '名', cn: '城市，街道' },
        { kana: 'ところ', mana: '所', type: '名', cn: '场所' },
        { kana: 'おみせ', mana: 'お店', type: '名', cn: '餐馆，商店' },
        { kana: 'にんぎょう', mana: '人形', type: '名', cn: '玩偶' },
        { kana: 'さくひん', mana: '作品', type: '名', cn: '作品' },
        { kana: 'ちょうこく', mana: '彫刻', type: '名', cn: '雕刻' },
        { kana: 'じどうしゃ', mana: '自動車', type: '名', cn: '汽车' },
        { kana: 'どうぐ', mana: '道具', type: '名', cn: '工具' },
        { kana: 'さかな', mana: '魚', type: '名', cn: '鱼' },
        { kana: 'おかし', mana: 'お菓子', type: '名', cn: '点心' },
        { kana: 'もの', mana: '物', type: '名', cn: '物品，东西' },
        { kana: 'シーズン', mana: '', type: '名', cn: '季节' },
        { kana: 'しゅうがくりょこう', mana: '修学旅行', type: '名', cn: '修学旅行' },
        { kana: 'かんこうきゃく', mana: '観光客', type: '名', cn: '游客' },
        { kana: 'さっか', mana: '作家', type: '名', cn: '作家' },
        { kana: 'ぶちょう', mana: '部長', type: '名', cn: '部长' },
        { kana: 'へいじつ', mana: '平日', type: '名', cn: '平日，非休息日' },
        { kana: 'ひ', mana: '日', type: '名', cn: '日子' },
        { kana: 'せいかつ', mana: '生活', type: '名', cn: '生活' },
        { kana: 'せかい', mana: '世界', type: '名', cn: '世界' },
        { kana: 'はれ', mana: '晴れ', type: '名', cn: '晴天' },
        { kana: 'あめ', mana: '雨', type: '名', cn: '雨，下雨' },
        { kana: 'くもり', mana: '曇り', type: '名', cn: '阴天' },
        { kana: 'ゆき', mana: '雪', type: '名', cn: '雪' },
        { kana: 'きたない', mana: '汚い', type: '形1', cn: '脏' },
        { kana: 'きれい', mana: '', type: '形2', cn: '漂亮，干净' },
        { kana: 'ゆうめい', mana: '有名', type: '形2', cn: '有名' },
        { kana: 'にぎやか', mana: '', type: '形2', cn: '热闹，繁华' },
        { kana: 'しずか', mana: '静か', type: '形2', cn: '安静' },
        { kana: 'ひま', mana: '暇', type: '形2', cn: '空闲' },
        { kana: 'しんせつ', mana: '親切', type: '形2', cn: '热情' },
        { kana: 'すき', mana: '好き', type: '形2', cn: '喜欢' },
        { kana: 'きらい', mana: '嫌い', type: '形2', cn: '讨厌' },
        { kana: 'べんり', mana: '便利', type: '形2', cn: '方便' },
        { kana: 'ふべん', mana: '不便', type: '形2', cn: '不方便' },
        { kana: 'げんき', mana: '元気', type: '形2', cn: '健康，有精神' },
        { kana: 'かんたん', mana: '簡単', type: '形2', cn: '简单' },
        { kana: 'ハンサム', mana: '', type: '形2', cn: '英俊，帅气' },
        { kana: 'どんな', mana: '', type: '疑', cn: '什么样的，怎样的' },
        { kana: 'どう', mana: '', type: '副', cn: '怎样，如何' },
        { kana: 'いかが', mana: '', type: '副', cn: '如何' },
        { kana: 'いろいろ', mana: '', type: '副', cn: '各种各样' },
        { kana: 'でも', mana: '', type: '连', cn: '可是，不过' },
        { kana: 'そして', mana: '', type: '连', cn: '而且，于是' },
        { kana: 'ところで', mana: '', type: '连', cn: '（转换话题）哎' },
        { kana: 'あれえ', mana: '', type: '叹', cn: '咦' },
        { kana: 'なら', mana: '奈良', type: '专', cn: '奈良' },
        { kana: 'ふじさん', mana: '富士山', type: '专', cn: '富士山' }
      ],
      phrase: [
        { kana: 'もうすこし', mana: 'もう少し', cn: '再～一点' },
        { kana: '〜中', mana: '', cn: '' }
      ]
    },
    {
      no: 11,
      topic: '小野さんは歌が好きです',
      basic: [],
      utilization: [],
      grammar: [],
      word: [
        { kana: 'うた', mana: '歌', type: '名', cn: '歌，歌曲' },
        { kana: 'カラオケ', mana: '', type: '名', cn: '卡拉OK' },
        { kana: 'ロック', mana: '', type: '名', cn: '摇滚乐' },
        { kana: 'ポップス', mana: '', type: '名', cn: '流行音乐' },
        { kana: 'クラシック', mana: '', type: '名', cn: '西方古典音乐' },
        { kana: 'ピアノ', mana: '', type: '名', cn: '钢琴' },
        { kana: 'え', mana: '絵', type: '名', cn: '画儿' },
        { kana: 'えいご', mana: '英語', type: '名', cn: '英语' },
        { kana: 'スペインご', mana: 'スペイン語', type: '名', cn: '西班牙语' },
        { kana: 'スポーツ', mana: '', type: '名', cn: '体育，运动' },
        { kana: 'すいえい', mana: '水泳', type: '名', cn: '游泳' },
        { kana: 'ゴルフ', mana: '', type: '名', cn: '高尔夫球' },
        { kana: 'うんてん', mana: '運転', type: '名', cn: '开车' },
        { kana: 'のみもの', mana: '飲み物', type: '名', cn: '饮料' },
        { kana: 'おさけ', mana: 'お酒', type: '名', cn: '酒，酒类' },
        { kana: 'にく', mana: '肉', type: '名', cn: '肉' },
        { kana: 'やさい', mana: '野菜', type: '名', cn: '蔬菜' },
        { kana: 'くだもの', mana: '果物', type: '名', cn: '水果' },
        { kana: 'ヒマワリ', mana: '', type: '名', cn: '向日葵' },
        { kana: 'バラ', mana: '', type: '名', cn: '蔷薇，玫瑰' },
        { kana: 'コンピュータ', mana: '', type: '名', cn: '计算机，电脑' },
        { kana: 'まど', mana: '窓', type: '名', cn: '窗，窗户' },
        { kana: 'けっこんしき', mana: '結婚式', type: '名', cn: '结婚典礼' },
        { kana: 'しゃしんてん', mana: '写真展', type: '名', cn: '摄影展' },
        { kana: 'りょかん', mana: '旅館', type: '名', cn: '旅馆，旅店' },
        { kana: 'べっそう', mana: '別荘', type: '名', cn: '别墅' },
        { kana: 'よせぎざいく', mana: '寄木細工', type: '名', cn: '木片儿拼花工艺品' },
        { kana: 'もよう', mana: '模様', type: '名', cn: '花纹，纹案' },
        { kana: 'がいこく', mana: '外国', type: '名', cn: '外国' },
        { kana: 'かいぎ', mana: '会議', type: '名', cn: '会议' },
        { kana: 'あし', mana: '脚', type: '名', cn: '腿' },
        { kana: 'ぼく', mana: '', type: '代', cn: '我（男性自称）' },
        { kana: 'わかります', mana: '分かります', type: '动1', cn: '懂，明白' },
        { kana: 'まよいます', mana: '迷います', type: '动1', cn: '犹豫，难以决定' },
        { kana: 'できます', mana: '', type: '动2', cn: '会；能；完成' },
        { kana: 'しめます', mana: '閉めます', type: '动2', cn: '关闭，关门' },
        { kana: 'つかれます', mana: '疲れます', type: '动2', cn: '疲倦，疲惫' },
        { kana: 'さんぽします', mana: '散歩します', type: '动3', cn: '散步' },
        { kana: 'こわい', mana: '怖い', type: '形1', cn: '害怕，恐怖' },
        { kana: 'あかい', mana: '赤い', type: '形1', cn: '红' },
        { kana: 'いたい', mana: '痛い', type: '形1', cn: '疼，疼痛' },
        { kana: 'じょうず', mana: '上手', type: '形2', cn: '擅长，高明，水平高' },
        { kana: 'へた', mana: '下手', type: '形2', cn: '不高明，水平低' },
        { kana: 'にがて', mana: '苦手', type: '形2', cn: '不擅长，不善于' },
        { kana: 'ときどき', mana: '時々', type: '副', cn: '有时，时不时' },
        { kana: 'よく', mana: '', type: '副', cn: '经常，常常' },
        { kana: 'たまに', mana: '', type: '副', cn: '偶尔，很少' },
        { kana: 'また', mana: '', type: '副', cn: '还，再，又' },
        { kana: 'どうして', mana: '', type: '副', cn: '为什么' },
        { kana: 'だから', mana: '', type: '连', cn: '所以，因此' },
        { kana: 'ですから', mana: '', type: '连', cn: '所以，因此' },
        { kana: 'うーん', mana: '', type: '叹', cn: '嗯……，这个……' }
      ],
      phrase: [
        { kana: 'けっこうです', mana: '結構です', cn: '不用，不要' },
        { kana: 'きにいります', mana: '気に入ります', cn: '中意，喜欢' },
        { kana: 'など', mana: '', cn: '等等' }
      ]
    },
    {
      no: 12,
      topic: '李さんは森さんより若いです',
      basic: [],
      utilization: [],
      grammar: [],
      word: [
        { kana: 'きせつ', mana: '季節', type: '名', cn: '季节' },
        { kana: 'ふゆ', mana: '冬', type: '名', cn: '冬天，冬季' },
        { kana: 'はる', mana: '春', type: '名', cn: '春天，春季' },
        { kana: 'にほんりょうり', mana: '日本料理', type: '名', cn: '日式饭菜' },
        { kana: 'すし', mana: '寿司', type: '名', cn: '寿司' },
        { kana: 'ナシ', mana: '', type: '名', cn: '梨' },
        { kana: 'バナナ', mana: '', type: '名', cn: '香蕉' },
        { kana: 'ミカン', mana: '', type: '名', cn: '橘子' },
        { kana: 'しょうちゅう', mana: '焼酎', type: '名', cn: '烧酒' },
        { kana: 'にほんしゅ', mana: '日本酒', type: '名', cn: '日本酒' },
        { kana: 'こうちゃ', mana: '紅茶', type: '名', cn: '红茶' },
        { kana: 'ウーロンちゃ', mana: 'ウーロン茶', type: '名', cn: '乌龙茶' },
        { kana: 'ジャスミンちゃ', mana: 'ジャスミン茶', type: '名', cn: '茉莉花茶' },
        { kana: 'りょくちゃ', mana: '緑茶', type: '名', cn: '绿茶' },
        { kana: 'ジュース', mana: '', type: '名', cn: '果汁' },
        { kana: 'にんき', mana: '人気', type: '名', cn: '声望，受欢迎' },
        { kana: 'せき', mana: '席', type: '名', cn: '座位，席位' },
        { kana: 'クラス', mana: '', type: '名', cn: '班级' },
        { kana: 'しゅるい', mana: '種類', type: '名', cn: '种类' },
        { kana: 'せ', mana: '背', type: '名', cn: '个人' },
        { kana: 'あに', mana: '兄', type: '名', cn: '哥哥，兄长' },
        { kana: 'さいきん', mana: '最近', type: '名', cn: '最近，近来' },
        { kana: 'ふります', mana: '降ります', type: '动1', cn: '下（雨，雪），降（雨，雪）' },
        { kana: 'わかい', mana: '若い', type: '形1', cn: '年轻' },
        { kana: 'あたたかい', mana: '暖かい', type: '形1', cn: '暖和，温暖' },
        { kana: 'すずしい', mana: '涼しい', type: '形1', cn: '凉爽' },
        { kana: 'はやい', mana: '速い', type: '形1', cn: '快' },
        { kana: 'だいすき', mana: '大好き', type: '形2', cn: '非常喜欢' },
        { kana: 'いちばん', mana: '', type: '副', cn: '最，第一' },
        { kana: 'ずっと', mana: '', type: '副', cn: '～得多' },
        { kana: 'やはり', mana: '', type: '副', cn: '仍然，还是' },
        { kana: 'やっぱり', mana: '', type: '副', cn: '仍然，还是' },
        { kana: 'チョモランマ', mana: '', type: '专', cn: '珠穆朗玛峰' }
      ],
      phrase: [
        { kana: 'にんきがあります', mana: '人気があります', cn: '受欢迎' },
        { kana: '〜年間', mana: '', cn: '' }
      ]
    }
  ]
}
