export default {
  chapter: 5,
  title: '小李在日本迎新春',
  lesson: [
    {
      no: 17,
      topic: 'わたしは新しい洋服が欲しいです',
      basic: [],
      utilization: [],
      grammar: [],
      word: [
        { kana: 'ようふく', mana: '洋服', type: '名', cn: '西服' },
        { kana: 'セーター', mana: '', type: '名', cn: '毛衣' },
        { kana: 'ノートパソコン', mana: '', type: '名', cn: '笔记本电脑' },
        { kana: 'バイク', mana: '', type: '名', cn: '摩托车' },
        { kana: 'おしるこ', mana: 'お汁粉', type: '名', cn: '年糕小豆汤' },
        { kana: 'てんぷら', mana: '天ぷら', type: '名', cn: '天麸罗' },
        { kana: 'はつもうで', mana: '初詣', type: '名', cn: '新年后首次参拜' },
        { kana: 'けんこう', mana: '健康', type: '名', cn: '健康' },
        { kana: 'れんあい', mana: '恋愛', type: '名', cn: '恋爱' },
        { kana: 'ドラマ', mana: '', type: '名', cn: '连续剧' },
        { kana: 'あいて', mana: '相手', type: '名', cn: '对象，对方' },
        { kana: 'こいびと', mana: '恋人', type: '名', cn: '恋人' },
        { kana: 'せんぱい', mana: '先輩', type: '名', cn: '前辈' },
        { kana: 'だんせい', mana: '男性', type: '名', cn: '男性' },
        { kana: 'がいこくじん', mana: '外国人', type: '名', cn: '外国人' },
        { kana: 'なつ', mana: '夏', type: '名', cn: '夏天' },
        { kana: 'ことし', mana: '今年', type: '名', cn: '今年' },
        { kana: 'はじめます', mana: '初めます', type: '动2', cn: '开始' },
        { kana: 'れんらくします', mana: '連絡します', type: '动3', cn: '联系' },
        { kana: 'ほしい', mana: '欲しい', type: '形1', cn: '想要' },
        { kana: 'りっぱ', mana: '立派', type: '形2', cn: '美观，杰出' },
        { kana: 'こんど', mana: '今度', type: '副', cn: '下次；这回' },
        { kana: 'ぜひ', mana: '', type: '副', cn: '一定' },
        { kana: 'そろそろ', mana: '', type: '副', cn: '快要' },
        { kana: 'まず', mana: '', type: '副', cn: '先，首先' },
        { kana: 'ベートーベン', mana: '', type: '专', cn: '贝多芬' },
        { kana: 'ショパン', mana: '', type: '专', cn: '肖邦' },
        { kana: 'こきゅう', mana: '故宮', type: '专', cn: '故宫' },
        { kana: 'ヨーロッパ', mana: '', type: '专', cn: '欧洲' },
        { kana: 'ホンコン', mana: '香港', type: '专', cn: '香港' },
        { kana: 'スイス', mana: '', type: '专', cn: '瑞士' }
      ],
      phrase: [
        { kana: '〜じゅうに', mana: '〜中に', cn: '' }
      ]
    },
    {
      no: 18,
      topic: '携帯電話はとても小さくなりました',
      basic: [],
      utilization: [],
      grammar: [],
      word: [
        { kana: 'おと', mana: '音', type: '名', cn: '声音，响声' },
        { kana: 'こえ', mana: '声', type: '名', cn: '声音' },
        { kana: 'くうき', mana: '空気', type: '名', cn: '空气' },
        { kana: 'むすこ', mana: '息子', type: '名', cn: '儿子' },
        { kana: 'いしゃ', mana: '医者', type: '名', cn: '医生' },
        { kana: 'おじょうさん', mana: 'お嬢さん', type: '名', cn: '令爱' },
        { kana: 'しゃかいじん', mana: '社会人', type: '名', cn: '社会的一员，成人' },
        { kana: 'りょこうガイド', mana: '旅行ガイド', type: '名', cn: '旅行导游' },
        { kana: 'がくしゃ', mana: '学者', type: '名', cn: '学者' },
        { kana: 'パイロット', mana: '', type: '名', cn: '飞行员' },
        { kana: 'デザイナー', mana: '', type: '名', cn: '设计者，设计家' },
        { kana: 'タイムサービス', mana: '', type: '名', cn: '时段廉价销售' },
        { kana: 'しんしゅんセール', mana: '新春セール', type: '名', cn: '新年大甩卖' },
        { kana: 'さんわりびき', mana: '3割引', type: '名', cn: '七折' },
        { kana: 'ていか', mana: '定価', type: '名', cn: '定价' },
        { kana: 'はんがく', mana: '半額', type: '名', cn: '半价' },
        { kana: 'ねだん', mana: '値段', type: '名', cn: '价格' },
        { kana: 'シャツ', mana: '', type: '名', cn: '衬衫' },
        { kana: 'スカート', mana: '', type: '名', cn: '裙子' },
        { kana: 'いろ', mana: '色', type: '名', cn: '颜色' },
        { kana: 'あか', mana: '赤', type: '名', cn: '红色' },
        { kana: 'あお', mana: '青', type: '名', cn: '蓝色' },
        { kana: 'おしょうがつ', mana: 'お正月', type: '名', cn: '过年，新年' },
        { kana: 'じかん', mana: '時間', type: '名', cn: '时间' },
        { kana: 'しょうらい', mana: '将来', type: '名', cn: '将来' },
        { kana: 'じゅんび', mana: '準備', type: '名', cn: '准备' },
        { kana: 'びょうき', mana: '病気', type: '名', cn: '疾病' },
        { kana: 'なります', mana: '', type: '动1', cn: '变，当，变成，成为' },
        { kana: 'あきます', mana: '開きます', type: '动1', cn: '开' },
        { kana: 'にあいます', mana: '似合います', type: '动1', cn: '适合，相称' },
        { kana: 'うるさい', mana: '', type: '形1', cn: '闹，使人心烦' },
        { kana: 'シンプル', mana: '', type: '动2', cn: '单纯，简洁' },
        { kana: 'まもなく', mana: '間もなく', type: '副', cn: '马上，一会儿，不久' },
        { kana: 'もうすぐ', mana: '', type: '副', cn: '马上' },
        { kana: 'さらに', mana: '', type: '副', cn: '更加，更' },
        { kana: 'もっと', mana: '', type: '副', cn: '更加，更' },
        { kana: 'さあ', mana: '', type: '叹', cn: '啊，喂' }
      ],
      phrase: [
        { kana: 'できるだけ', mana: '', cn: '尽量，尽可能' },
        { kana: 'もとめて', mana: '', cn: '一下子，一起，汇总，汇集' },
        { kana: 'いまから', mana: '今から', cn: '从现在起' }
      ]
    },
    {
      no: 19,
      topic: '部屋のかぎを忘れないでください',
      basic: [],
      utilization: [],
      grammar: [],
      word: [
        { kana: 'しなもの', mana: '品物', type: '名', cn: '物品，商品' },
        { kana: 'おさら', mana: 'お皿', type: '名', cn: '盘子' },
        { kana: 'ごみ', mana: '', type: '名', cn: '垃圾' },
        { kana: 'しょしんしゃ', mana: '初心者', type: '名', cn: '初学者' },
        { kana: 'じょうきゅうしゃ', mana: '上級者', type: '名', cn: '熟练者' },
        { kana: 'こうきゅう', mana: '高級', type: '名', cn: '高级' },
        { kana: 'じょうきゅうクラス', mana: '上級クラス', type: '名', cn: '高级班' },
        { kana: 'えいかいわ', mana: '英会話', type: '名', cn: '英语会话' },
        { kana: 'コース', mana: '', type: '名', cn: '路线，滑道' },
        { kana: 'スキー', mana: '', type: '名', cn: '滑雪' },
        { kana: 'レポート', mana: '', type: '名', cn: '报告' },
        { kana: 'パスポート', mana: '', type: '名', cn: '护照' },
        { kana: 'のど', mana: '', type: '名', cn: '喉咙' },
        { kana: 'さわります', mana: '触ります', type: '动1', cn: '碰，触' },
        { kana: 'ぬぎます', mana: '脱ぎます', type: '动1', cn: '脱' },
        { kana: 'ころびます', mana: '転びます', type: '动1', cn: '摔，摔倒，跌倒' },
        { kana: 'かわきます', mana: '渇きます', type: '动1', cn: '渴' },
        { kana: 'なおります', mana: '治ります', type: '动1', cn: '痊愈，医好' },
        { kana: 'すべります', mana: '滑ります', type: '动1', cn: '滑，滑行' },
        { kana: 'よびます', mana: '呼びます', type: '动1', cn: '呼喊' },
        { kana: 'かえします', mana: '返します', type: '动1', cn: '归还' },
        { kana: 'てつだいます', mana: '手伝います', type: '动1', cn: '帮忙' },
        { kana: 'はこびます', mana: '運びます', type: '动1', cn: '搬运' },
        { kana: 'なくします', mana: '', type: '动1', cn: '丢，丢失' },
        { kana: 'おとします', mana: '落とします', type: '动1', cn: '掉，使落下' },
        { kana: 'おきます', mana: '置きます', type: '动1', cn: '放置' },
        { kana: 'はらいます', mana: '払います', type: '动1', cn: '支付' },
        { kana: 'たちます', mana: '立ちます', type: '动1', cn: '站，立' },
        { kana: 'わすれます', mana: '忘れます', type: '动2', cn: '忘记' },
        { kana: 'あわてます', mana: '慌てます', type: '动2', cn: '慌张，惊慌，着急' },
        { kana: 'すてます', mana: '捨てます', type: '动2', cn: '扔，扔掉' },
        { kana: 'ざんぎょうします', mana: '残業します', type: '动3', cn: '加班' },
        { kana: 'しんぱいします', mana: '心配します', type: '动3', cn: '担心' },
        { kana: 'ほんとう', mana: '本当', type: '形2', cn: '真的，真正' },
        { kana: 'はやく', mana: '早く', type: '副', cn: '早点儿' },
        { kana: 'やっと', mana: '', type: '副', cn: '好不容易，终于' },
        { kana: 'だいぶ', mana: '', type: '副', cn: '很，相当地' },
        { kana: 'はじめて', mana: '初めて', type: '副', cn: '第一次' },
        { kana: 'さきに', mana: '先に', type: '副', cn: '先' },
        { kana: 'やまだ', mana: '山田', type: '专', cn: '山田' }
      ],
      phrase: [
      ]
    },
    {
      no: 20,
      topic: 'スミスさんはピアノを弾くことができます',
      basic: [],
      utilization: [],
      grammar: [],
      word: [
        { kana: 'しゅみ', mana: '趣味', type: '名', cn: '爱好' },
        { kana: 'とくぎ', mana: '特技', type: '名', cn: '特长，拿手的技术' },
        { kana: 'きょうみ', mana: '興味', type: '名', cn: '兴趣' },
        { kana: 'ゆめ', mana: '夢', type: '名', cn: '梦；理想' },
        { kana: 'ギター', mana: '', type: '名', cn: '吉他' },
        { kana: 'こきゅう', mana: '胡弓', type: '名', cn: '胡琴' },
        { kana: 'しょどう', mana: '書道', type: '名', cn: '书法' },
        { kana: 'つり', mana: '釣り', type: '名', cn: '钓鱼' },
        { kana: 'ドライブ', mana: '', type: '名', cn: '兜风，开汽车远游' },
        { kana: 'あみもの', mana: '編み物', type: '名', cn: '编织；编织品' },
        { kana: 'てづくり', mana: '手作り', type: '名', cn: '手工做，自己做，手制' },
        { kana: 'ちゅうかがい', mana: '中華街', type: '名', cn: '中华街' },
        { kana: 'ちゅうかりょうり', mana: '中華料理', type: '名', cn: '中国菜' },
        { kana: 'ギョーザ', mana: '餃子', type: '名', cn: '饺子' },
        { kana: 'かわ', mana: '皮', type: '名', cn: '皮' },
        { kana: 'しゅんせつ', mana: '春節', type: '名', cn: '春节' },
        { kana: 'ししまい', mana: '獅子舞', type: '名', cn: '狮子舞' },
        { kana: 'りょう', mana: '寮', type: '名', cn: '宿舍' },
        { kana: 'せんたくき', mana: '洗濯機', type: '名', cn: '洗衣机' },
        { kana: 'シャワー', mana: '', type: '名', cn: '淋浴' },
        { kana: 'おなか', mana: '', type: '名', cn: '肚子' },
        { kana: 'じゅぎょう', mana: '授業', type: '名', cn: '授课，上课' },
        { kana: 'しりょう', mana: '資料', type: '名', cn: '资料' },
        { kana: 'フランスご', mana: 'フランス語', type: '名', cn: '法语' },
        { kana: 'しょうせつ', mana: '小説', type: '名', cn: '小说' },
        { kana: 'かいがん', mana: '海岸', type: '名', cn: '海岸' },
        { kana: 'ふゆやすみ', mana: '冬休み', type: '名', cn: '寒假' },
        { kana: 'キャンプ', mana: '', type: '名', cn: '野营' },
        { kana: 'みんな', mana: '', type: '名', cn: '大家' },
        { kana: 'じぶん', mana: '自分', type: '名', cn: '自己' },
        { kana: 'ぜんいん', mana: '全員', type: '名', cn: '全员' },
        { kana: 'ひきます', mana: '弾きます', type: '动1', cn: '弹' },
        { kana: 'すきます', mana: '', type: '动1', cn: '（肚子）饿，空' },
        { kana: 'のぼります', mana: '登ります', type: '动1', cn: '登，上' },
        { kana: 'あつめます', mana: '集めます', type: '动2', cn: '收集' },
        { kana: 'あびます', mana: '浴びます', type: '动2', cn: '淋；浇' },
        { kana: 'ごちそうします', mana: '', type: '动3', cn: '请客，摆盛宴' },
        { kana: 'きこくします', mana: '帰国します', type: '动3', cn: '回国' },
        { kana: 'とくに', mana: '特に', type: '副', cn: '特别' }
      ],
      phrase: [
        { kana: 'おなかがすきます', mana: '', cn: '肚子饿' }
      ]
    }
  ]
}
