export default {
  id: 11,
  chapter: 11,
  title: '在北京的工作情况',
  lesson: [
    {
      no: 41,
      topic: '李さんは部長にほめられました',
      basic: {},
      utilization: {},
      grammar: {},
      word: [
        { kana: 'ことり', mana: '小鳥', type: '名', cn: '小鸟，鸟儿' },
        { kana: 'ばんぱく', mana: '万博', type: '名', cn: '世博会，万国博览会' },
        { kana: 'いせき', mana: '遺跡', type: '名', cn: '遗迹，遗址' },
        { kana: 'じょうし', mana: '上司', type: '名', cn: '上司' },
        { kana: 'すり', mana: '', type: '名', cn: '扒手，小偷' },
        { kana: 'せだい', mana: '世代', type: '名', cn: '世代；一代' },
        { kana: 'しじょう', mana: '市場', type: '名', cn: '市场' },
        { kana: 'ちょうさ', mana: '調査', type: '名', cn: '调查' },
        { kana: 'しゅっか', mana: '出荷', type: '名', cn: '上市，运出货物' },
        { kana: 'せいちょう', mana: '成長', type: '名', cn: '成长' },
        { kana: 'あらし', mana: '嵐', type: '名', cn: '暴风雨，风暴' },
        { kana: 'ダイナマイト', mana: '', type: '名', cn: '炸药' },
        { kana: 'ネーミング', mana: '', type: '名', cn: '名称，命名，取名' },
        { kana: 'コストダウン', mana: '', type: '名', cn: '降低成本' },
        { kana: 'ていかかく', mana: '低価格', type: '名', cn: '低价（格）' },
        { kana: 'ぎゅうにく', mana: '牛肉', type: '名', cn: '牛肉' },
        { kana: 'いっさくねん', mana: '一昨年', type: '名', cn: '前年' },
        { kana: 'おととし', mana: '', type: '名', cn: '前年' },
        { kana: 'さくねん', mana: '昨年', type: '名', cn: '去年' },
        { kana: 'こんご', mana: '今後', type: '名', cn: '今后' },
        { kana: 'すべて', mana: '', type: '名', cn: '全部，所有' },
        { kana: 'びしょぬれ', mana: '', type: '名', cn: '落汤鸡，湿透，濡湿' },
        { kana: 'みりょく', mana: '魅力', type: '名', cn: '吸引力，魅力' },
        { kana: 'おしょくじけん', mana: '汚職事件', type: '名', cn: '贪污事件' },
        { kana: 'しじょうちょうさ', mana: '市場調査', type: '名', cn: '市场调查' },
        { kana: 'こうつうじじょう', mana: '交通事情', type: '名', cn: '交通状况' },
        { kana: 'ごうべんがいしゃ', mana: '合弁会社', type: '名', cn: '合资公司' },
        { kana: 'しかります', mana: '', type: '动1', cn: '训，责备，斥责' },
        { kana: 'かみます', mana: '', type: '动1', cn: '咬，嚼' },
        { kana: 'さそいます', mana: '誘います', type: '动1', cn: '邀请，约请' },
        { kana: 'まきこみます', mana: '巻き込みます', type: '动1', cn: '卷入，卷进' },
        { kana: 'いたります', mana: '至ります', type: '动1', cn: '到达，达到' },
        { kana: 'みつかります', mana: '見つかります', type: '动1', cn: '找到，发现' },
        { kana: 'ふみます', mana: '踏みます', type: '动1', cn: '踩，踏' },
        { kana: 'はかります', mana: '図ります', type: '动1', cn: '谋求；考虑' },
        { kana: 'みこみます', mana: '見込みます', type: '动1', cn: '预料，估计' },
        { kana: 'ぬすみます', mana: '盗みます', type: '动1', cn: '盗取，偷盗' },
        { kana: 'おこします', mana: '起こします', type: '动1', cn: '叫醒，唤醒' },
        { kana: 'ほめます', mana: '', type: '动2', cn: '表扬，赞扬' },
        { kana: 'もとめます', mana: '求めます', type: '动2', cn: '要求；追求，寻求' },
        { kana: 'いじめます', mana: '', type: '动2', cn: '欺负，折磨，欺侮' },
        { kana: 'ぶつけます', mana: '', type: '动2', cn: '碰上，撞上；扔，投，掷' },
        { kana: 'はっけんします', mana: '発見します', type: '动3', cn: '发现' },
        { kana: 'じしょくします', mana: '辞職します', type: '动3', cn: '辞职' },
        { kana: 'そうりつします', mana: '創立します', type: '动3', cn: '成立，创立' },
        { kana: 'いらいします', mana: '依頼します', type: '动3', cn: '委托，请求' },
        { kana: 'はつばいします', mana: '発売します', type: '动3', cn: '上市，发售，出售' },
        { kana: 'かいはつします', mana: '開発します', type: '动3', cn: '开发' },
        { kana: 'せいぞうします', mana: '製造します', type: '动3', cn: '生产，制造' },
        { kana: 'かんりします', mana: '管理します', type: '动3', cn: '管理' },
        { kana: 'じつげんします', mana: '実現します', type: '动3', cn: '实现' },
        { kana: 'せんれんします', mana: '洗練します', type: '动3', cn: '精炼，洗练' },
        { kana: 'ほうそうします', mana: '放送します', type: '动3', cn: '广播，播送' },
        { kana: 'せいさんします', mana: '生産します', type: '动3', cn: '生产' },
        { kana: 'ほんやくします', mana: '翻訳します', type: '动3', cn: '翻译，笔译' },
        { kana: 'はつめいします', mana: '発明します', type: '动3', cn: '发明' },
        { kana: 'はばひろい', mana: '幅広い', type: '形1', cn: '广泛，宽广，辽阔' },
        { kana: 'おおはば', mana: '大幅', type: '形2', cn: '大事（度），广泛' },
        { kana: 'たいりょう', mana: '大量', type: '形2', cn: '大量' },
        { kana: 'もっとも', mana: '最も', type: '副', cn: '最' },
        { kana: 'いやあ', mana: '', type: '叹', cn: '哎呀' },
        { kana: 'ニュートン', mana: '', type: '专', cn: '牛顿' },
        { kana: 'ノーベル', mana: '', type: '专', cn: '诺贝尔' },
        { kana: 'オーストラリア', mana: '', type: '专', cn: '澳大利亚' },
        { kana: 'シーエスコンス', mana: 'CS公司', type: '专', cn: 'CS公司' },
        { kana: 'チンタオビール', mana: '青島ビール', type: '专', cn: '青岛啤酒' },
        { kana: 'あキューせいでん', mana: '阿Q正伝', type: '专', cn: '阿Q正传' }
      ],
      phrase: [
        { kana: 'まいりました', mana: '参りました', cn: '真糟糕，真倒霉' },
        { kana: 'ばんゆういんりょくのほうそく', mana: '万有引力の法則', cn: '万有引力定律' }
      ]
    },
    {
      no: 42,
      topic: 'テレビをつけたまま、出かけてしまいました',
      basic: {},
      utilization: {},
      grammar: {},
      word: [
        { kana: 'せきにんしゃ', mana: '責任者', type: '名', cn: '负责人' },
        { kana: 'どうりょう', mana: '同僚', type: '名', cn: '同事' },
        { kana: 'かんきゃく', mana: '観客', type: '名', cn: '观众' },
        { kana: 'くうふく', mana: '空腹', type: '名', cn: '空肚子，空腹，饿' },
        { kana: 'かんき', mana: '換気', type: '名', cn: '换气' },
        { kana: 'るす', mana: '留守', type: '名', cn: '不在家' },
        { kana: 'こうどう', mana: '講堂', type: '名', cn: '讲堂' },
        { kana: 'ひるま', mana: '昼間', type: '名', cn: '白天，白日' },
        { kana: 'にってい', mana: '日程', type: '名', cn: '日程' },
        { kana: 'じかい', mana: '次回', type: '名', cn: '下次，下回' },
        { kana: 'めざまし', mana: '目覚まし', type: '名', cn: '闹钟；叫醒' },
        { kana: 'アラーム', mana: '', type: '名', cn: '闹钟，闹铃' },
        { kana: 'きかくあん', mana: '企画案', type: '名', cn: '策划方案' },
        { kana: 'おへんじ', mana: 'お返事', type: '名', cn: '回信' },
        { kana: 'いきさき', mana: '行き先', type: '名', cn: '去的地方，目的地' },
        { kana: 'あずかります', mana: '預かります', type: '动1', cn: '保管，收存' },
        { kana: 'きづきます', mana: '気づきます', type: '动1', cn: '发觉，发现' },
        { kana: 'ひやします', mana: '冷やします', type: '动1', cn: '冰镇，冷却' },
        { kana: 'おもいだします', mana: '思い出します', type: '动1', cn: '想起，想出' },
        { kana: 'つげます', mana: '告げます', type: '动2', cn: '说，告诉' },
        { kana: 'ひえます', mana: '冷えます', type: '动2', cn: '变冷；感觉凉' },
        { kana: 'しんじます', mana: '信じます', type: '动2', cn: '相信，信任' },
        { kana: 'おれます', mana: '折れます', type: '动2', cn: '折，断；拐弯' },
        { kana: 'しゅっきんします', mana: '出勤します', type: '动3', cn: '上班，出勤' },
        { kana: 'セットします', mana: '', type: '动3', cn: '设定，设置' },
        { kana: 'けんとうします', mana: '検討します', type: '动3', cn: '讨论' },
        { kana: 'ただしい', mana: '正しい', type: '形1', cn: '正确的' },
        { kana: 'とうぜん', mana: '当然', type: '形2', cn: '当然，应当' },
        { kana: 'たしか', mana: '確か', type: '形2', cn: '确实，确切；大概' },
        { kana: 'じょうぶ', mana: '丈夫', type: '形2', cn: '牢固，结实' },
        { kana: 'さっそく', mana: '早速', type: '副', cn: '马上，立即' },
        { kana: 'ちょくせつ', mana: '直接', type: '副', cn: '直接' },
        { kana: 'きっと', mana: '', type: '副', cn: '一定' },
        { kana: 'だって', mana: '', type: '连', cn: '可是，但是' },
        { kana: 'にしちょうあんがい', mana: '西長安街', type: '专', cn: '西长安街' }
      ],
      phrase: [
        { kana: 'るすにします', mana: '留守にします', cn: '不在家，无人在家' }
      ]
    },
    {
      no: 43,
      topic: '陳さんは息子をアメリカに留学させます',
      basic: {},
      utilization: {},
      grammar: {},
      word: [
        { kana: 'おてつだい', mana: 'お手伝い', type: '名', cn: '帮忙，帮助' },
        { kana: 'のりかえ', mana: '乗り換え', type: '名', cn: '换车，换乘' },
        { kana: 'かんがえ', mana: '考え', type: '名', cn: '想法，思想' },
        { kana: 'じょせいむけ', mana: '女性向け', type: '名', cn: '女性专用，专为女性' },
        { kana: 'もうしで', mana: '申し出', type: '名', cn: '申请，提议' },
        { kana: 'かんじ', mana: '感じ', type: '名', cn: '感觉' },
        { kana: 'おおく', mana: '多く', type: '名', cn: '多，多数' },
        { kana: 'ぶか', mana: '部下', type: '名', cn: '部下' },
        { kana: 'かんとく', mana: '監督', type: '名', cn: '教练，领队' },
        { kana: 'せんしゅ', mana: '選手', type: '名', cn: '运动员，选手' },
        { kana: 'しょうひしゃ', mana: '消費者', type: '名', cn: '消费者' },
        { kana: 'あんないやく', mana: '案内役', type: '名', cn: '向导，导游' },
        { kana: 'おや', mana: '親', type: '名', cn: '双亲，父母' },
        { kana: 'プレゼンテーション', mana: '', type: '名', cn: '策划方案说明（会）' },
        { kana: 'プレゼン', mana: '', type: '名', cn: '策划方案说明（会）' },
        { kana: 'アルファベット', mana: '', type: '名', cn: '英语字母，拉丁字母' },
        { kana: 'イメージ', mana: '', type: '名', cn: '形象，印象' },
        { kana: 'インパクト', mana: '', type: '名', cn: '冲击力，力量感' },
        { kana: 'ガラス', mana: '', type: '名', cn: '玻璃，玻璃杯' },
        { kana: 'きぶん', mana: '気分', type: '名', cn: '（身体）舒适（与否）；情绪' },
        { kana: 'しんきんかん', mana: '親近感', type: '名', cn: '亲切感' },
        { kana: 'ひんしつ', mana: '品質', type: '名', cn: '质量，品质' },
        { kana: 'ぶっか', mana: '物価', type: '名', cn: '物价' },
        { kana: 'めんぜいてん', mana: '免税店', type: '名', cn: '免税店' },
        { kana: 'せつめいしょ', mana: '説明書', type: '名', cn: '说明书' },
        { kana: 'じゅく', mana: '塾', type: '名', cn: '私塾，补习学校' },
        { kana: 'れいぶん', mana: '例文', type: '名', cn: '例句' },
        { kana: 'かいじょう', mana: '会場', type: '名', cn: '会场' },
        { kana: 'せつび', mana: '設備', type: '名', cn: '设备' },
        { kana: 'せんたくもの', mana: '洗濯物', type: '名', cn: '洗的衣服' },
        { kana: 'もの', mana: '', type: '名', cn: '东西，事物' },
        { kana: 'じ', mana: '字', type: '名', cn: '字' },
        { kana: 'つま', mana: '妻', type: '名', cn: '妻子' },
        { kana: 'われわれ', mana: '我々', type: '代', cn: '我们' },
        { kana: 'ひっぱります', mana: '引っ張ります', type: '动1', cn: '拉，拽' },
        { kana: 'うかびます', mana: '浮かびます', type: '动1', cn: '想起，浮，浮现' },
        { kana: 'ととのいます', mana: '整います', type: '动1', cn: '齐备，完备' },
        { kana: 'かわきます', mana: '乾きます', type: '动1', cn: '干，干燥' },
        { kana: 'くらします', mana: '暮らします', type: '动1', cn: '生活' },
        { kana: 'さけます', mana: '避けます', type: '动2', cn: '回避，避免' },
        { kana: 'うれます', mana: '売れます', type: '动2', cn: '好卖，畅销' },
        { kana: 'うけます', mana: '受けます', type: '动2', cn: '感受，受到' },
        { kana: 'あたためます', mana: '温めます', type: '动2', cn: '热，温' },
        { kana: 'りかいします', mana: '理解します', type: '动3', cn: '理解' },
        { kana: 'ていあんします', mana: '提案します', type: '动3', cn: '建议，提案' },
        { kana: 'しさくします', mana: '試作します', type: '动3', cn: '试作，试制' },
        { kana: 'けいけんします', mana: '経験します', type: '动3', cn: '经验，经历' },
        { kana: 'あんきします', mana: '暗記します', type: '动3', cn: '熟记，背诵' },
        { kana: 'そうたいします', mana: '早退します', type: '动3', cn: '早退' },
        { kana: 'きゅうしょくします', mana: '休職します', type: '动3', cn: '（暂时）停职' },
        { kana: 'ちからづよい', mana: '力強い', type: '形1', cn: '强有力；心里踏实' },
        { kana: 'やわらかい', mana: '柔らかい', type: '形1', cn: '柔软' },
        { kana: 'かたい', mana: '硬い', type: '形1', cn: '硬' },
        { kana: 'あつい', mana: '厚い', type: '形1', cn: '厚' },
        { kana: 'じゅうよう', mana: '重要', type: '形2', cn: '重要' },
        { kana: 'たんじゅん', mana: '単純', type: '形2', cn: '单纯' },
        { kana: 'りそうてき', mana: '理想的', type: '形2', cn: '理想' },
        { kana: 'ぐたいてき', mana: '具体的', type: '形2', cn: '具体' },
        { kana: 'ざんしん', mana: '斬新', type: '形2', cn: '新颖，崭新' },
        { kana: 'ぐっと', mana: '', type: '副', cn: '更加；用力' },
        { kana: 'たとえば', mana: '例えば', type: '副', cn: '比如，例如' },
        { kana: 'しかも', mana: '', type: '连', cn: '而且' },
        { kana: 'そこで', mana: '', type: '连', cn: '因此，于是，所以；那么' }
      ],
      phrase: [
        { kana: 'いうまでもなく', mana: '言うまでもなく', cn: '不言而喻' },
        { kana: '〜なんか', mana: '', cn: '' }
      ]
    },
    {
      no: 44,
      topic: '玄関のところにだれかいるようです',
      basic: {},
      utilization: {},
      grammar: {},
      word: [
        { kana: 'しゃいんりょこう', mana: '社員旅行', type: '名', cn: '员工旅行' },
        { kana: 'しんにゅうしゃいん', mana: '新入社員', type: '名', cn: '新来的职员' },
        { kana: 'かいぎじょう', mana: '会議場', type: '名', cn: '会场' },
        { kana: 'こくさいかいぎ', mana: '国際会議', type: '名', cn: '国际会议' },
        { kana: 'ビアガーデン', mana: '', type: '名', cn: '庭院式的啤酒店' },
        { kana: 'おおがたスーパー', mana: '大型スーパー', type: '名', cn: '大型超市' },
        { kana: 'みずうみ', mana: '湖', type: '名', cn: '湖' },
        { kana: 'パトカー', mana: '', type: '名', cn: '警车，巡逻车' },
        { kana: 'サイレン', mana: '', type: '名', cn: '警笛，警报器' },
        { kana: 'アニメ', mana: '', type: '名', cn: '动画片' },
        { kana: 'パワー', mana: '', type: '名', cn: '能力，力量' },
        { kana: 'こころ', mana: '心', type: '名', cn: '心' },
        { kana: 'たいど', mana: '態度', type: '名', cn: '态度' },
        { kana: 'せいかく', mana: '性格', type: '名', cn: '性格' },
        { kana: 'ひょうばん', mana: '評判', type: '名', cn: '评价，评论' },
        { kana: 'ぎょうれつ', mana: '行列', type: '名', cn: '行列，队伍' },
        { kana: 'ようき', mana: '容器', type: '名', cn: '容器' },
        { kana: 'ないよう', mana: '内容', type: '名', cn: '内容' },
        { kana: 'うれゆき', mana: '売れ行き', type: '名', cn: '销路，销售（情况）' },
        { kana: 'のりもの', mana: '乗り物', type: '名', cn: '交通工具' },
        { kana: 'あせ', mana: '汗', type: '名', cn: '汗' },
        { kana: 'ばい', mana: '倍', type: '名', cn: '倍，加倍' },
        { kana: 'たて', mana: '縦', type: '名', cn: '纵，竖' },
        { kana: 'ちゅうごくぜんど', mana: '中国全土', type: '名', cn: '全中国' },
        { kana: 'ちょうきよほう', mana: '長期予報', type: '名', cn: '长期预报' },
        { kana: 'わらい', mana: '笑い', type: '名', cn: '笑' },
        { kana: 'あつさ', mana: '暑さ', type: '名', cn: '暑热，暑气' },
        { kana: 'うつくしさ', mana: '美しさ', type: '名', cn: '美好，美丽程度' },
        { kana: 'おもしろさ', mana: '', type: '名', cn: '趣味，有趣程度' },
        { kana: 'おおきさ', mana: '大きさ', type: '名', cn: '大小' },
        { kana: 'たかさ', mana: '高さ', type: '名', cn: '高度' },
        { kana: 'ふかさ', mana: '深さ', type: '名', cn: '深度' },
        { kana: 'ながさ', mana: '長さ', type: '名', cn: '长度' },
        { kana: 'ひろさ', mana: '広さ', type: '名', cn: '面积' },
        { kana: 'ふとさ', mana: '太さ', type: '名', cn: '粗（度）' },
        { kana: 'おもさ', mana: '重さ', type: '名', cn: '重量' },
        { kana: 'あつさ', mana: '厚さ', type: '名', cn: '厚度' },
        { kana: 'はやさ', mana: '速さ', type: '名', cn: '速度' },
        { kana: 'べんりさ', mana: '便利さ', type: '名', cn: '方便程度' },
        { kana: 'ふくざつさ', mana: '複雑さ', type: '名', cn: '复杂程度' },
        { kana: 'おいしさ', mana: '', type: '名', cn: '美味，好吃程度' },
        { kana: 'じゅうようさ', mana: '重要さ', type: '名', cn: '重要性，重要程度' },
        { kana: 'あまさ', mana: '甘さ', type: '名', cn: '甜度' },
        { kana: 'ひろがります', mana: '広がります', type: '动1', cn: '蔓延，拓宽' },
        { kana: 'もどります', mana: '戻ります', type: '动1', cn: '返回，回到' },
        { kana: 'おどろきます', mana: '驚きます', type: '动1', cn: '惊讶，吃惊' },
        { kana: 'しゃれます', mana: '', type: '动2', cn: '别致，风趣；打扮得漂亮' },
        { kana: 'じっかんします', mana: '実感します', type: '动3', cn: '切实感受，真切感受' },
        { kana: 'ふかい', mana: '深い', type: '形1', cn: '深' },
        { kana: 'おとなしい', mana: '', type: '形1', cn: '温顺，老实' },
        { kana: 'はずかしい', mana: '恥ずかしい', type: '形1', cn: '害羞，难为情' },
        { kana: 'めずらしい', mana: '珍しい', type: '形1', cn: '珍奇，新奇' },
        { kana: 'ごうか', mana: '豪華', type: '形2', cn: '豪华，奢华' },
        { kana: 'こうちょう', mana: '好調', type: '形2', cn: '顺利，情况良好' },
        { kana: 'ひかえめ', mana: '控えめ', type: '形2', cn: '分量少，节制，控制；拘谨' },
        { kana: 'こうひょう', mana: '好評', type: '形2', cn: '好评，称赞' },
        { kana: 'だいじ', mana: '大事', type: '形2', cn: '重要，宝贵' },
        { kana: 'かなり', mana: '', type: '副', cn: '颇，相当' },
        { kana: 'けっこう', mana: '', type: '副', cn: '很，相当' },
        { kana: 'ささき', mana: '佐々木', type: '专', cn: '佐佐木' },
        { kana: 'びわこ', mana: '琵琶湖', type: '专', cn: '琵琶湖' },
        { kana: 'のぞみ', mana: '', type: '专', cn: '“希望号”' }
      ],
      phrase: [
        { kana: 'おかげさまで', mana: '', cn: '托您的福' },
        { kana: 'なんといっても', mana: '何と言っても', cn: '首先是，无论如何' },
        { kana: '〜キロ', mana: '', cn: '' },
        { kana: '〜キログラム', mana: '', cn: '' },
        { kana: '〜センチ', mana: '', cn: '' }
      ]
    }
  ]
}
